services:
  lectcal:
    build: .
    container_name: lectcal
    restart: always
    environment:
      SONS_URL: ${SONS_URL}
    volumes:
      - ${SONS_HOST_DIR}:/usr/share/nginx/html/sons:ro
    networks:
      - web

networks:
  web:
    external: true
