services:
  lectcal:
    build: .
    container_name: lectcal
    restart: always
    volumes:
      - /var/app/lectcal/sons:/usr/share/nginx/html/sons:ro
    networks:
      - web

networks:
  web:
    external: true
